#application: "alexsher311013" 
#version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: bot.app

- url: /set_webhook
  login: admin
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: ssl
  version: latest
